on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    # At 02:30 on Saturday
    - cron: "30 2 * * 6"

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_version: [26, 27, 28]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}

      - name: Build and push container image (v${{ matrix.docker_version }})
        uses: docker/build-push-action@v6
        with:
          context: docker
          build-args: |
            DOCKER_VERSION=${{ matrix.docker_version }}
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:v${{ matrix.docker_version }}
            ${{ matrix.docker_version == 28 && format('{0}/{1}:latest', vars.REGISTRY, vars.IMAGE_NAME) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-swarm-stack-templates:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish
        uses: Josh5/action.publish-swarm-stack@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          templates_path: docker-swarm-templates
          branch_name: release/latest
